# Generated by Django 5.1.3 on 2024-11-13 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivriety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chaivriety',
            name='date_aded',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 15, 6, 48, 161621, tzinfo=datetime.timezone.utc)),
        ),
    ]
