# Generated by Django 5.1.3 on 2024-11-15 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_alter_chaivriety_date_aded_chaicertificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaireview',
            old_name='date_Added',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='chaivriety',
            name='date_aded',
        ),
        migrations.AddField(
            model_name='chaivriety',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chaivriety',
            name='type',
            field=models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('KL', 'KIWI'), ('PL', 'PLAIN'), ('EL', 'ELAICHI')], max_length=2),
        ),
    ]
